HBS/HBS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Hotel.urls',namespace="Hotel")),
]

static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

HBS/Hotel/urls.py
import django
from . import views
from django.urls import path,include
from django.contrib.auth import views as auth_views 
from django.urls import reverse_lazy

app_name = 'Hotel'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('password-change/',auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('Hotel:password_change_done')),name='password_change'),
    path('passwor-change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
    path('password-reset/',auth_views.PasswordResetView.as_view(success_url=reverse_lazy('Hotel:password_reset_done')),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('Hotel:password_reset_complete')),name='password_reset_confirm'),
    path('password-reset/complete/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('register/',views.register,name='register'),
    # path('email_verification',views),
    path('room_details/',views.room_details,name='room_details'),
    path('booking_form/',views.booking_form,name='booking_form'),
    # path('booking.html/',views.room_details,name='booking')
    # path('booking_conformation.html',views.booking_confromation,name='booking_conformation'),
    path('room_details/available_rooms_searching/<int:year>/<int:month>/<int:day>/<int:year2>/<int:month2>/<int:day2>/',views.available_rooms_searching,name='available_rooms_searching'),
    path('',views.dashboard,name='dashboard'),
    path('showbookings',views.showbookings,name='showbookings'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('aboutus',views.aboutus,name='aboutus'),
    path('contact',views.contact,name='contact'),
    path('cancelbooking/<int:id>',views.cancelbooking,name='cancelbooking'),
    # path('webhook/',views.my_webhook_view,name='webhook'),
    path('editprofile/',views.editprofile,name='editprofile'),
    path('invoice/<int:id>',views.invoice,name='invoice'),
    path('gallary',views.gallery,name="gallery"),
    path('printcancel/<int:id>',views.printcancel,name="printcancel"),
    path('cancellation/',views.cancellation,name='cancellation'),
]

HBS/Hotel/models.py
from typing import Iterable
from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

User._meta.get_field('email')._unique = True
User._meta.get_field('email').blank = False
User._meta.get_field('email').null = False

# Create your models here.
class room(models.Model):
    class Type(models.TextChoices):
        King_Size_Four_Poster = "King Size Four Poster"
        King_Size_Sleigh_Bed = "King Size Sleigh Bed"
        Deluxe_King_Size = "Deluxe King Size"
        Deluxe_Twin_Large_Double = "Deluxe Twin/Large Double"
        Compact_Double = "Compact Double"
        Family_Room ="Family Room"
        Single = "Single"
    room_image = models.ImageField(upload_to='static/images')
    room_no = models.CharField(max_length=4,unique=True)
    room_description = models.TextField()
    room_type = models.CharField(max_length=24,choices=Type.choices,default=Type.Single)
    beds = models.IntegerField(default=1)
    capasity = models.IntegerField(default=2)
    current_price_pernight = models.IntegerField(default=800)
    is_boocked = models.BooleanField(default=False)

    def __str__(self):
        return self.room_no
    
    def get_url(self):
        return reverse("Hotel:booking_form",args=[self.room_no])
    
class booking(models.Model):
    gauest_username = models.ForeignKey(User,on_delete=models.CASCADE)
    room_no = models.ForeignKey(room,on_delete=models.CASCADE)
    check_in = models.DateField(null=True,default=None)
    check_out = models.DateField(null=True,default=None)
    total_price = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return f'{self.gauest_username} has booked {self.room_no} from {self.check_in} to {self.check_out}'
    
    def url(self):
        return reverse("Hotel:cancelbooking",args=[self.id])
    def get_invoice_url(self):
        return reverse("Hotel:invoice",args=[self.id])
    
class cancellation_info(models.Model):
    gauest_username = models.ForeignKey(User,on_delete=models.CASCADE)
    room_no = models.ForeignKey(room,on_delete=models.CASCADE)
    check_in = models.DateField(null=True,default=None)
    check_out = models.DateField(null=True,default=None)
    total_price = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True, blank=True)
    

HBS/Hotel/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth.models import User
from django.urls import reverse
from .models import booking,room

# class LoginForm(forms.Form):
#     Username = forms.CharField(required=True)
#     Password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Password don't match.")
        return cd['password2']
    

class bookingform(forms.ModelForm):
    First_name = forms.CharField()
    Last_name = forms.CharField()
    Email = forms.EmailField()
    Room_no = forms.IntegerField()
    Room_type = forms.CharField()
    Beds = forms.IntegerField()
    Capasity = forms.IntegerField()
    class Meta:
        model = booking
        fields = ['check_in','check_out','total_price']


class searchform(forms.Form):
    checkin = forms.DateField(widget=forms.NumberInput(attrs={'type':'date'}))
    checkout = forms.DateField(widget=forms.NumberInput(attrs={'type':'date'}))

    def get_url(self,year,month,day,year2,month2,day2):
        return reverse("Hotel:available_rooms_searching",args=[year,month,day,year2,month2,day2])

class roomform(forms.ModelForm):
    class Meta:
        model = room
        fields = ['room_no','room_type','beds','capasity','current_price_pernight']

HBS/Hotel/views.py
from decimal import Decimal
from io import BytesIO
from django.conf import settings
from django.core.mail import EmailMessage
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from HBS import settings
from django.conf import settings
from django.template.loader import render_to_string
import weasyprint
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt
from .forms import UserRegistrationForm,bookingform,searchform,roomform
from .functions import available_rooms,numberOfDays,remainig_days,calculate_days
from .models import room,booking,User,cancellation_info
from django import forms
import stripe
import datetime
from django.contrib import messages
import random
from datetime import date
# Create your views here.

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION
# check for the available rooms from checkin and checkout date
@login_required
def available_rooms_searching(request,year,month,day,year2,month2,day2):
        if request.method == "POST":
            if 'search' in request.POST:
                return redirect("Hotel:room_details")
            elif 'submit' in request.POST:
                print('submit in the request')
                room_no = request.POST.get('submit')
                start_date=(str)((str)(year)+"-"+(str)(month)+"-"+(str)(day))
                end_date=(str)((str)(year2)+"-"+(str)(month2)+"-"+(str)(day2))
                check_in_form = datetime.datetime.strptime(start_date,"%Y-%m-%d").date()
                check_out_form = datetime.datetime.strptime(end_date,"%Y-%m-%d").date()
                selected_room =room.objects.filter(room_no=room_no)
                amount = 0
                year = (check_out_form).year - (check_in_form).year
                month = (check_out_form).month - (check_in_form).month
                days = 0
                if month == 0 and year == 0:
                    days = (check_out_form).day - (check_in_form).day+1
                elif year == 0 :
                    month_days = numberOfDays((check_in_form).year,(check_in_form).month)
                    month_days2 =numberOfDays((check_out_form).year,(check_out_form).month)
                    days = month_days-(int)((check_in_form).day)+(int)((check_out_form).day)+1
                else:
                    days = remainig_days(check_in_form.year,check_in_form.month,check_in_form.day)+calculate_days(check_out_form.year,check_out_form.month,check_out_form.day)
                    print(days)
                for ro in selected_room:
                    selected_room=ro
                    amount = ro.current_price_pernight*days
                print(amount)
                check_in_form = check_in_form.strftime("%Y-%m-%d")
                check_out_form = check_out_form.strftime("%Y-%m-%d")
                print(check_in_form)
                return render(request,'payment/process.html',{'checkin':check_in_form,'checkout':check_out_form,'room':selected_room,'amount':amount,'section':'book_a_room'})
        start_date=(str)((str)(year)+"-"+(str)(month)+"-"+(str)(day))
        end_date=(str)((str)(year2)+"-"+(str)(month2)+"-"+(str)(day2))
        check_in_form = datetime.datetime.strptime(start_date,"%Y-%m-%d").date()
        check_out_form = datetime.datetime.strptime(end_date,"%Y-%m-%d").date()
        rooms = available_rooms(check_in_form=check_in_form,check_out_form=check_out_form)
        check = True
        print("hello i am back")
        check_in_form = check_in_form.strftime("%Y-%m-%d")
        check_out_form = check_out_form.strftime("%Y-%m-%d")
        print(check_in_form)
        return render(request,'Hotel/booking.html',{'rooms':rooms,'check_in':check_in_form,'check_out':check_out_form,'check':check,'section':'book_a_room'})
        # else:

        #     return HttpResponse("error")

        
        
def register(request):
    if request.user.is_authenticated:
        return render(request,"Hotel/dashboard.html",{'section':'dashboard'})
    else:
        if request.method == 'POST':
            if 'signup' in request.POST:
                user_form = UserRegistrationForm(request.POST)
                if user_form.is_valid():
                    new_user = user_form.save(commit=False)
                    new_user.set_password(user_form.cleaned_data['password'])
                    email = user_form.cleaned_data['email']
                    print(email)
                    otp = random.randint(111111,999999)
                    send_mail(
                        'Verifiction Mail For The Registration',
                        'This is a verification code for the registeration : '+(str)(otp),
                        'go229732@gmail.com',
                        [email],
                        fail_silently=False,
                    )
                    request.session['rotp']=otp
                    request.session['us']=new_user.username
                    request.session['fn']=new_user.first_name
                    request.session['ln']=new_user.last_name
                    request.session['e']=new_user.email
                    request.session['p']=new_user.password
                    # new_user.save()
                    check = True
                    return render(request,'Hotel/register_done.html',{'new_user':user_form,'check':check})
                else:
                    return render(request,'Hotel/register.html',{'user_form':user_form})
            elif 'veri' in request.POST:
                otp1 = request.POST.get('code')
                otp2 = request.session.get('rotp')
                new_user = request.POST.get('new_user')
                us = request.session.get('us')
                fn = request.session.get('fn')
                ln = request.session.get('ln')
                e = request.session.get('e')
                p = request.session.get('p')
                new_user=User(username = us,first_name = fn,last_name = ln,email=e,password=p)
                print(new_user)
                if((int)(otp1)==(int)(otp2)):
                    # print(new_user.username)
                    new_user.save()
                    return render(request,'Hotel/register_done.html')
                else:
                    check = True    
                    g= True 
                    return render(request,'Hotel/register_done.html',{'error':g,'check':check})
        else:
            user_form = UserRegistrationForm()
            return render(request,'Hotel/register.html',{'user_form':user_form})


@login_required
def dashboard(request):
    return render(request,"Hotel/dashboard.html",{'section':'dashboard'})

@login_required
def room_details(request):
    if request.method == 'POST':
            form = searchform(request.POST)
            if form.is_valid():
                check_in_form =  request.POST.get('checkin')
                check_out_form = request.POST.get('checkout')
                check_in_form = datetime.datetime.strptime(check_in_form,"%Y-%m-%d").date()
                check_out_form = datetime.datetime.strptime(check_out_form,"%Y-%m-%d").date()
                check_inyear=check_in_form.year
                check_inmonth = check_in_form.month
                check_inday = check_in_form.day
                check_outyear = check_out_form.year
                check_outmonth = check_out_form.month
                check_outday = check_out_form.day
                if check_in_form >=check_out_form:
                    error = "Atleast one day ofobooking is required"
                    if check_in_form>check_out_form:
                        error = "check in date must be less than the check out date"
                    return render(request,'Hotel/booking.html',{'form':form,'error':error,'section':'book_a_room'})
                elif check_in_form<date.today():
                    error = "Enter the proper checkin date"
                    return render(request,'Hotel/booking.html',{'form':form,'error':error,'section':'book_a_room'})
                url = form.get_url(check_inyear,check_inmonth,check_inday,check_outyear,check_outmonth,check_outday)
                print(url)
                return redirect(url)
            else:
                return render(request,'Hotel/booking.html',{'form':form})
    else:
        form = searchform()
        return render(request,'Hotel/booking.html',{'form':form,'section':'book_a_room'})
    
@login_required
def booking_form(request):
    if request.method == 'POST':
        form = bookingform(request.POST)
        if form.is_valid():
            check_in = request.POST.get('check_in')
            croom_no = request.POST.get('Room_no')
            ccheck_out = request.POST.get('check_out')
            ctotal_price = request.POST.get('total_price')
            cusername = request.POST.get('username')
            check_in = datetime.datetime.strptime(check_in,'%Y-%m-%d')
            ccheck_out = datetime.datetime.strptime(ccheck_out,'%Y-%m-%d')
            available = available_rooms(check_in_form=check_in,check_out_form=ccheck_out)
            croom_no = room.objects.get(room_no=croom_no)
            if croom_no in available:
                print("hello i am in booking form")
                croom_no.is_boocked = True
                print(croom_no.is_boocked)
                user = User.objects.get(username = cusername)
                new_booking = booking(gauest_username=user,room_no=croom_no,check_in=check_in,check_out=ccheck_out,total_price=ctotal_price)
                #payment process
                request.session['booking_room_no']=new_booking.room_no.room_no
                request.session['booking_check_in']=(str)(new_booking.check_in)
                request.session['booking_check_out']=(str)(new_booking.check_out)

HBS/Hotel/templates/Hotel/alreadydeleted.html
{% extends 'base.html' %}
{% block title %}
Already Canceled
{% endblock title %}
{% block content %}
<h1>Cancellation Information</h1>
<p>The selected room is already unbooked pls refresh the page</p>
{% endblock content %}

HBS/Hotel/templates/Hotel/booking_conformation.html
{% extends 'base.html' %}
{% block title %}Boocking conformation{% endblock title %}
{% block content %}
<h1>Boocking conformation</h1>
<p>Your room has been boocked succesfully!</p>
{% endblock content %}

HBS/Hotel/templates/Hotel/cancelation.html
{% extends 'base.html' %}
{% block title %}
Cancellation form
{% endblock title %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/pdf.css' %}">
<h1>Cancellation Info</h1>
<p>Your booking has been succesfully cancelled.</p>
<p>
    Cancellation id. {{booking.id}}<br>
    <span class="secondanary">
        Booking time: {{booking.created}}
    </span>
</p>
<h3>Bill to</h3>
<p>
    Name  :{{booking.gauest_username.first_name}} {{booking.gauest_username.last_name}}<br>
    Email : {{booking.gauest_username.email}}<br>
</p>
<h3>Booking information</h3>
<table>
    <thead>
        <tr>
            <th>Room No</th>
            <th>Room Type</th>
            <th>Price</th>
            <th>check in </th>
            <th>check out</th>
        </tr>
    </thead>
    <tbody>
        <tr class="row{% cycle "1" "2" %}">
            <td>{{booking.room_no.room_no}}</td>
            <td>{{booking.room_no.room_type}}</td>
            <td>{{booking.room_no.current_price_pernight}}₹</td>
            <td>{{booking.check_in}}</td>
            <td>{{booking.check_out}}</td>
        </tr>
        <tr class="total">
            <td colspan="4">Total amount </td>
            <td class="num">{{cancel.booking.total_price}}₹</td>
        </tr>
    </tbody>
</table>
<span class="pending">
    Canceled
</span>
<span>Your Amount Should Be Refunded Within a Week</span><br>
<p>You Can <a href="{% url 'Hotel:printcancel' id=booking.id %}">Print Cancellation info</a></p>
<p>You Can <a href="{% url 'Hotel:showbookings' %}">Show Your Bookings Here</a></p>
{% endblock content %}

HBS/Hotel/templates/Hotel/cancelationinfo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cancellation info</title>
    <link rel="stylesheet" href="{% static 'css/pdf.css' %}">
</head>
<body>

    <h1>Pride Plaza Hotel</h1>
    <p>
        Cancellation id. {{booking.id}}<br>
        <span class="secondanary">
            Booking time: {{booking.created}}
        </span>
    </p>
    <h3>Bill to</h3>
    <p>
        Name  :{{booking.gauest_username.first_name}} {{booking.gauest_username.last_name}}<br>
        Email : {{booking.gauest_username.email}}<br>
    </p>
    <h3>Booking information</h3>
    <table>
        <thead>
            <tr>
                <th>Room No</th>
                <th>Room Type</th>
                <th>Price</th>
                <th>check in </th>
                <th>check out</th>
            </tr>
        </thead>
        <tbody>
            <tr class="row{% cycle "1" "2" %}">
                <td>{{booking.room_no.room_no}}</td>
                <td>{{booking.room_no.room_type}}</td>
                <td>{{booking.room_no.current_price_pernight}}₹</td>
                <td>{{booking.check_in}}</td>
                <td>{{booking.check_out}}</td>
            </tr>
            <tr class="total">
                <td colspan="4">Total amount </td>
                <td class="num">{{booking.total_price}}₹</td>
            </tr>
        </tbody>
    </table>
    <span class="pending">
        Canceled
    </span>
    <span>Your Amount Should Be Refunded Within a Week</span>
</body>
</html>

HBS/Hotel/templates/Hotel/cancelledbooking.html
{% extends 'base.html' %}
{% block title %}Cancelled Booking{% endblock title %}
{% block content %}
    <style>
        table{
            font-family:Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 90%;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
            border-collapse: collapse;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
        }
        th{
            background: #509e74;
        }
        td,th{
            border: 2px solid #000000;
            text-align: center;
            padding: 15px;
        }
        tr:nth-child(even){
            background-color: #c9c9c9dd;
        }
        tr:hover{background-color:#a9a7a7;}
    </style>
<h1>Cancelled Booking Information</h1>
{% if not info %}
<p>No bookinngs cancelled by you</p>
{% comment %} <p>You can <a href="{% url 'Hotel:room_details' %}">Book a room</a><p> {% endcomment %}
{% else %}
<p>Here is your booking cancellation information</p>
<center>
    <form method = 'post'>
        <table>
            <tr>
                <th>Room Image</th>
                <th>Room No</th>
                <th>Room Type</th>
                <th>Check In</th>
                <th>Check Out</th>
                <th>Total Price</th>
                <th>cancellation info</th>
            </tr>
            {% for i in info  %}
                <tr>
                    {% comment %} {% for room in rooms %} {% endcomment %}
                        {% comment %} {% if room == i.room_no %} {% endcomment %}
                        <td><img src="{{i.room_no.room_image.url}}"  style="margin:9px" height=200px alt=""></td>
                        <td>{{i.room_no.room_no}}</td>
                        <td>{{i.room_no.room_type}}</td>
                        {% comment %} {% endif %} {% endcomment %}
                    {% comment %} {% endfor %} {% endcomment %}
                    <td>{{i.check_in}}</td>
                    <td>{{i.check_out}}</td>
                    <td>{{i.total_price}}₹</td>
                    <input type='hidden' value = {{i.total_price}} name = "print">
                    <td><b><a href="{% url 'Hotel:printcancel' i.id %}" type="submit"  style="color: rgb(43, 43, 195);">Print cancellation Bill</a></b><br><br>
                    <tr>
            {% endfor %}
        </table>
    </form>
</center>
{% endif %}
{% endblock content %}

HBS/Hotel/templates/Hotel/contact.html
{% extends 'base.html' %}
{% block title %}
Contact us 
{% endblock title %}
{% block content %}
    <style>
        /* * {
            box-sizing: border-box;
            font-family: Arial, sans-serif;
          } */
          
          /* .container {
            position: relative;
            padding: 0px 1200px 0px 0px;
          }
           */
          h1 {
            text-align: left;
            margin-bottom: 30px;
          }
          
          form {
            /* display: flex;
            flex-direction: column; */
            /* clear: both; */
          } 
          
          label {
            font-weight: bold;
            margin-bottom: 10px;
          }
          
          input, textarea {
            width: 35%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
          }
          
          textarea {
            height: 150px;
            resize:none;
          }
          
          button[type="submit"] {
            background-color: #12c064;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
          }
          
          button[type="submit"]:hover {
            background-color: green;
          }   
    </style>
    {% if done %}
    <h1>Thank you!</h1>
    <p>Your messege has been succesfully sended to the team.</p>
    {% else %}
    <h1>Contact Us</h1>
    <div class="container">
      <form action="#" method="POST">
        {% csrf_token %}
      <label for="name">Name:</label> 
      <input type="text" id="name"  name="name" required>
      <label for="email">Email:</label>
      <input type="email" id="email" disabled value = {{email}} name="email" required>
      <label for="message">Message:</label>
      <textarea id="message" name="message" required length='disabled'></textarea>
      <!-- <button type="submit">Send</button> -->
      <input style="cursor: pointer;width: 36.3%;" type="submit" value="Send">
    </form>
  </div>
  {% endif %}
{% endblock content %}

HBS/Hotel/templates/Hotel/editprofile.html
{% extends 'base.html' %}
{% block title %}
Edit Profile
{% endblock title %}
{% block content %}
<h1>Profile Information</h1>
<p>You can change your profile information below</p>
<form method='post'>
  {% if error %}
  <p style="color:#d75151;">{{error}}</p>
  {% endif %}
    <p>
            <label for="id_username">Username:</label>
        <input type="text" name="username" maxlength="150" value='{{username}}' required id="id_username">
    </p>
    <p>
        <label for="id_first_name">First name:</label>
        <input type="text" name="first_name" maxlength="150" value='{{first}}'required id="id_first_name">
      </p>
      <p>
        <label for="id_last_name">Last name:</label>
        <input type="text" name="last_name" maxlength="150" value='{{last}}' required id="id_last_name">
      </p>
      <p>
        <label for="id_email">Email address:</label>
        <input type="email" name="email" maxlength="254"  value='{{email}}' required id="id_email">
      </p>
      <br>
      <p><input type = 'submit'value='Save Changes'></p>
      {% csrf_token %}
</form>
{% comment %} <script type = "text/javascript" >  
  function preventBack() { window.history.forward(); }  
  setTimeout("preventBack()", 0);  
  window.onunload = function () { null };  
</script>  {% endcomment %}
{% endblock content %}

HBS/Hotel/templates/Hotel/error.html
{% extends 'base.html' %}
{% block title %}
error
{% endblock title %}
{% block content %}
<h1>Error Inforamtion</h1>
<p>Some error occured while payment pls try again</p>
{% endblock content %}

HBS/Hotel/templates/Hotel/net.html
{% extends 'base.html' %}
{% block title %}
Network Error
{% endblock title %}
{% block content %}
<h1>Network Conneciton Error</h1>
<p>Make sure you had active internet connection. You can <a href="Hotel:room_details">try agains</a></p>
{% endblock content %}

HBS/Hotel/templates/Hotel/profileverification.html
{% extends 'base.html' %}
{% block title %}
Update Profile
{% endblock title %}
{% block content %}
<style>
    /* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance: textfield;
}

</style>
{% if verified %}
<h1>Profile updation information</h1>
<p>Your profile has been succesfully updated.</p>
{% else %}
<h1>OTP Verification</h1>
<p>Enter the otp sent to your updated mail</p>
<form method = 'post'>
    {% csrf_token %}
    {% if error %}
    <p style='color:#d75151;'>Pls enter the otp sent to the your email address</p>
    {% endif %}
    <p><input type='number' pattern="/^-?\d+\.?\d*$/" onKeyPress="if(this.value.length==6) return false;" required name ='code'>
        <input type='submit'  name = 'verify' value ='Verify'>
    </p>
</form>
{% comment %} <script type = "text/javascript" >  
    function preventBack() { window.history.forward(); }  
    setTimeout("preventBack()", 0);  
    window.onunload = function () { null };  
</script>  {% endcomment %}
{% endif %}
{% endblock content %}

HBS/Hotel/templates/Hotel/register_done.html
{% extends 'base.html' %}
{% block title %}Welcome{% endblock title %}
{% block content %}
{% if check %}
<h1>OTP Verification</h1>
<p>Enter the otp sent to your mail</p>
<form method = 'post'>
    {% csrf_token %}
    {% if error %}
    <p style='color:#d75151;'>Pls enter the otp sent to the your email address</p>
    {% endif %}
    <p><input type='number' required name ='code'>
        <p><input type='hidden' value='{{new_user.usrname}}' name ='new_user'>
        <input type='submit' name = 'veri' value ='Verify'>
    </p>
</form>
{% else %}
<h1>Welcome {{new_user.first_name}}!</h1>
<p>Your account has been succesfully created.
    Now you can <a href="{% url 'Hotel:login' %}">log in</a>
</p>
{% endif %}
{% endblock content %}