HBS/HBS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Hotel.urls',namespace="Hotel")),
]

static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

HBS/Hotel/urls.py
import django
from . import views
from django.urls import path,include
from django.contrib.auth import views as auth_views 
from django.urls import reverse_lazy

app_name = 'Hotel'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('password-change/',auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('Hotel:password_change_done')),name='password_change'),
    path('passwor-change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
    path('password-reset/',auth_views.PasswordResetView.as_view(success_url=reverse_lazy('Hotel:password_reset_done')),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('Hotel:password_reset_complete')),name='password_reset_confirm'),
    path('password-reset/complete/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('register/',views.register,name='register'),
    # path('email_verification',views),
    path('room_details/',views.room_details,name='room_details'),
    path('booking_form/',views.booking_form,name='booking_form'),
    # path('booking.html/',views.room_details,name='booking')
    # path('booking_conformation.html',views.booking_confromation,name='booking_conformation'),
    path('room_details/available_rooms_searching/<int:year>/<int:month>/<int:day>/<int:year2>/<int:month2>/<int:day2>/',views.available_rooms_searching,name='available_rooms_searching'),
    path('',views.dashboard,name='dashboard'),
    path('showbookings',views.showbookings,name='showbookings'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('aboutus',views.aboutus,name='aboutus'),
    path('contact',views.contact,name='contact'),
    path('cancelbooking/<int:id>',views.cancelbooking,name='cancelbooking'),
    # path('webhook/',views.my_webhook_view,name='webhook'),
    path('editprofile/',views.editprofile,name='editprofile'),
    path('invoice/<int:id>',views.invoice,name='invoice'),
    path('gallary',views.gallery,name="gallery"),
    path('printcancel/<int:id>',views.printcancel,name="printcancel"),
    path('cancellation/',views.cancellation,name='cancellation'),
]

HBS/Hotel/models.py
from typing import Iterable
from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

User._meta.get_field('email')._unique = True
User._meta.get_field('email').blank = False
User._meta.get_field('email').null = False

# Create your models here.
class room(models.Model):
    class Type(models.TextChoices):
        King_Size_Four_Poster = "King Size Four Poster"
        King_Size_Sleigh_Bed = "King Size Sleigh Bed"
        Deluxe_King_Size = "Deluxe King Size"
        Deluxe_Twin_Large_Double = "Deluxe Twin/Large Double"
        Compact_Double = "Compact Double"
        Family_Room ="Family Room"
        Single = "Single"
    room_image = models.ImageField(upload_to='static/images')
    room_no = models.CharField(max_length=4,unique=True)
    room_description = models.TextField()
    room_type = models.CharField(max_length=24,choices=Type.choices,default=Type.Single)
    beds = models.IntegerField(default=1)
    capasity = models.IntegerField(default=2)
    current_price_pernight = models.IntegerField(default=800)
    is_boocked = models.BooleanField(default=False)

    def __str__(self):
        return self.room_no
    
    def get_url(self):
        return reverse("Hotel:booking_form",args=[self.room_no])
    
class booking(models.Model):
    gauest_username = models.ForeignKey(User,on_delete=models.CASCADE)
    room_no = models.ForeignKey(room,on_delete=models.CASCADE)
    check_in = models.DateField(null=True,default=None)
    check_out = models.DateField(null=True,default=None)
    total_price = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return f'{self.gauest_username} has booked {self.room_no} from {self.check_in} to {self.check_out}'
    
    def url(self):
        return reverse("Hotel:cancelbooking",args=[self.id])
    def get_invoice_url(self):
        return reverse("Hotel:invoice",args=[self.id])
    
class cancellation_info(models.Model):
    gauest_username = models.ForeignKey(User,on_delete=models.CASCADE)
    room_no = models.ForeignKey(room,on_delete=models.CASCADE)
    check_in = models.DateField(null=True,default=None)
    check_out = models.DateField(null=True,default=None)
    total_price = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True, blank=True)
    

HBS/Hotel/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth.models import User
from django.urls import reverse
from .models import booking,room

# class LoginForm(forms.Form):
#     Username = forms.CharField(required=True)
#     Password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Password don't match.")
        return cd['password2']
    

class bookingform(forms.ModelForm):
    First_name = forms.CharField()
    Last_name = forms.CharField()
    Email = forms.EmailField()
    Room_no = forms.IntegerField()
    Room_type = forms.CharField()
    Beds = forms.IntegerField()
    Capasity = forms.IntegerField()
    class Meta:
        model = booking
        fields = ['check_in','check_out','total_price']


class searchform(forms.Form):
    checkin = forms.DateField(widget=forms.NumberInput(attrs={'type':'date'}))
    checkout = forms.DateField(widget=forms.NumberInput(attrs={'type':'date'}))

    def get_url(self,year,month,day,year2,month2,day2):
        return reverse("Hotel:available_rooms_searching",args=[year,month,day,year2,month2,day2])

class roomform(forms.ModelForm):
    class Meta:
        model = room
        fields = ['room_no','room_type','beds','capasity','current_price_pernight']

HBS/Hotel/views.py
from decimal import Decimal
from io import BytesIO
from django.conf import settings
from django.core.mail import EmailMessage
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from HBS import settings
from django.conf import settings
from django.template.loader import render_to_string
import weasyprint
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt
from .forms import UserRegistrationForm,bookingform,searchform,roomform
from .functions import available_rooms,numberOfDays,remainig_days,calculate_days
from .models import room,booking,User,cancellation_info
from django import forms
import stripe
import datetime
from django.contrib import messages
import random
from datetime import date
# Create your views here.

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION
# check for the available rooms from checkin and checkout date
@login_required
def available_rooms_searching(request,year,month,day,year2,month2,day2):
        if request.method == "POST":
            if 'search' in request.POST:
                return redirect("Hotel:room_details")
            elif 'submit' in request.POST:
                print('submit in the request')
                room_no = request.POST.get('submit')
                start_date=(str)((str)(year)+"-"+(str)(month)+"-"+(str)(day))
                end_date=(str)((str)(year2)+"-"+(str)(month2)+"-"+(str)(day2))
                check_in_form = datetime.datetime.strptime(start_date,"%Y-%m-%d").date()
                check_out_form = datetime.datetime.strptime(end_date,"%Y-%m-%d").date()
                selected_room =room.objects.filter(room_no=room_no)
                amount = 0
                year = (check_out_form).year - (check_in_form).year
                month = (check_out_form).month - (check_in_form).month
                days = 0
                if month == 0 and year == 0:
                    days = (check_out_form).day - (check_in_form).day+1
                elif year == 0 :
                    month_days = numberOfDays((check_in_form).year,(check_in_form).month)
                    month_days2 =numberOfDays((check_out_form).year,(check_out_form).month)
                    days = month_days-(int)((check_in_form).day)+(int)((check_out_form).day)+1
                else:
                    days = remainig_days(check_in_form.year,check_in_form.month,check_in_form.day)+calculate_days(check_out_form.year,check_out_form.month,check_out_form.day)
                    print(days)
                for ro in selected_room:
                    selected_room=ro
                    amount = ro.current_price_pernight*days
                print(amount)
                check_in_form = check_in_form.strftime("%Y-%m-%d")
                check_out_form = check_out_form.strftime("%Y-%m-%d")
                print(check_in_form)
                return render(request,'payment/process.html',{'checkin':check_in_form,'checkout':check_out_form,'room':selected_room,'amount':amount,'section':'book_a_room'})
        start_date=(str)((str)(year)+"-"+(str)(month)+"-"+(str)(day))
        end_date=(str)((str)(year2)+"-"+(str)(month2)+"-"+(str)(day2))
        check_in_form = datetime.datetime.strptime(start_date,"%Y-%m-%d").date()
        check_out_form = datetime.datetime.strptime(end_date,"%Y-%m-%d").date()
        rooms = available_rooms(check_in_form=check_in_form,check_out_form=check_out_form)
        check = True
        print("hello i am back")
        check_in_form = check_in_form.strftime("%Y-%m-%d")
        check_out_form = check_out_form.strftime("%Y-%m-%d")
        print(check_in_form)
        return render(request,'Hotel/booking.html',{'rooms':rooms,'check_in':check_in_form,'check_out':check_out_form,'check':check,'section':'book_a_room'})
        # else:

        #     return HttpResponse("error")

        
        
def register(request):
    if request.user.is_authenticated:
        return render(request,"Hotel/dashboard.html",{'section':'dashboard'})
    else:
        if request.method == 'POST':
            if 'signup' in request.POST:
                user_form = UserRegistrationForm(request.POST)
                if user_form.is_valid():
                    new_user = user_form.save(commit=False)
                    new_user.set_password(user_form.cleaned_data['password'])
                    email = user_form.cleaned_data['email']
                    print(email)
                    otp = random.randint(111111,999999)
                    send_mail(
                        'Verifiction Mail For The Registration',
                        'This is a verification code for the registeration : '+(str)(otp),
                        'go229732@gmail.com',
                        [email],
                        fail_silently=False,
                    )
                    request.session['rotp']=otp
                    request.session['us']=new_user.username
                    request.session['fn']=new_user.first_name
                    request.session['ln']=new_user.last_name
                    request.session['e']=new_user.email
                    request.session['p']=new_user.password
                    # new_user.save()
                    check = True
                    return render(request,'Hotel/register_done.html',{'new_user':user_form,'check':check})
                else:
                    return render(request,'Hotel/register.html',{'user_form':user_form})
            elif 'veri' in request.POST:
                otp1 = request.POST.get('code')
                otp2 = request.session.get('rotp')
                new_user = request.POST.get('new_user')
                us = request.session.get('us')
                fn = request.session.get('fn')
                ln = request.session.get('ln')
                e = request.session.get('e')
                p = request.session.get('p')
                new_user=User(username = us,first_name = fn,last_name = ln,email=e,password=p)
                print(new_user)
                if((int)(otp1)==(int)(otp2)):
                    # print(new_user.username)
                    new_user.save()
                    return render(request,'Hotel/register_done.html')
                else:
                    check = True    
                    g= True 
                    return render(request,'Hotel/register_done.html',{'error':g,'check':check})
        else:
            user_form = UserRegistrationForm()
            return render(request,'Hotel/register.html',{'user_form':user_form})


@login_required
def dashboard(request):
    return render(request,"Hotel/dashboard.html",{'section':'dashboard'})

@login_required
def room_details(request):
    if request.method == 'POST':
            form = searchform(request.POST)
            if form.is_valid():
                check_in_form =  request.POST.get('checkin')
                check_out_form = request.POST.get('checkout')
                check_in_form = datetime.datetime.strptime(check_in_form,"%Y-%m-%d").date()
                check_out_form = datetime.datetime.strptime(check_out_form,"%Y-%m-%d").date()
                check_inyear=check_in_form.year
                check_inmonth = check_in_form.month
                check_inday = check_in_form.day
                check_outyear = check_out_form.year
                check_outmonth = check_out_form.month
                check_outday = check_out_form.day
                if check_in_form >=check_out_form:
                    error = "Atleast one day ofobooking is required"
                    if check_in_form>check_out_form:
                        error = "check in date must be less than the check out date"
                    return render(request,'Hotel/booking.html',{'form':form,'error':error,'section':'book_a_room'})
                elif check_in_form<date.today():
                    error = "Enter the proper checkin date"
                    return render(request,'Hotel/booking.html',{'form':form,'error':error,'section':'book_a_room'})
                url = form.get_url(check_inyear,check_inmonth,check_inday,check_outyear,check_outmonth,check_outday)
                print(url)
                return redirect(url)
            else:
                return render(request,'Hotel/booking.html',{'form':form})
    else:
        form = searchform()
        return render(request,'Hotel/booking.html',{'form':form,'section':'book_a_room'})
    
@login_required
def booking_form(request):
    if request.method == 'POST':
        form = bookingform(request.POST)
        if form.is_valid():
            check_in = request.POST.get('check_in')
            croom_no = request.POST.get('Room_no')
            ccheck_out = request.POST.get('check_out')
            ctotal_price = request.POST.get('total_price')
            cusername = request.POST.get('username')
            check_in = datetime.datetime.strptime(check_in,'%Y-%m-%d')
            ccheck_out = datetime.datetime.strptime(ccheck_out,'%Y-%m-%d')
            available = available_rooms(check_in_form=check_in,check_out_form=ccheck_out)
            croom_no = room.objects.get(room_no=croom_no)
            if croom_no in available:
                print("hello i am in booking form")
                croom_no.is_boocked = True
                print(croom_no.is_boocked)
                user = User.objects.get(username = cusername)
                new_booking = booking(gauest_username=user,room_no=croom_no,check_in=check_in,check_out=ccheck_out,total_price=ctotal_price)
                #payment process
                request.session['booking_room_no']=new_booking.room_no.room_no
                request.session['booking_check_in']=(str)(new_booking.check_in)
                request.session['booking_check_out']=(str)(new_booking.check_out)

HBS/Hotel/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock  %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">  
    </head>
    <style>

        footer{
            background-color: hsl(113, 46%, 85%);
            position: relative;
            bottom: -110px;
            /* left: 0;
            right: 0; */
            width: 100%;
        }
        p{
            color: #71302d;
        }
        .fa{
            padding: 10px;
            font-size: 30px;
            width: 40px;
            text-align: center;
            text-decoration: none;
            margin: 5px 2px;
            color: white;
        }
        .fa:hover {
    opacity: 1;
}
        .fa.fa-facebook{
            background-color: black;
            border-radius: 15px;
        }
        .fa.fa-youtube{
            background-color: black;
            border-radius: 15px;
        }
        .fa.fa-instagram{
            background-color: black;
            border-radius: 15px;
        }
        .fa.fa-linkedin{
            background-color: black;
            border-radius: 15px;
        }
        .fa.fa-twitter{
            background-color: black;
            border-radius: 15px;
        }
        #foo{
            font-size: larger;
            font-weight: bolder;
            position: relative;
            top: 40px;

        }
        #fodiv{
            display:inline-block;
            position: relative;
            top: 0px;
        }
        .fa.fa-youtube:hover{
            background-color: #bb0000;
        }
        .fa.fa.fa-instagram:hover{ background-color:rgb(206, 67, 199);}
        .fa.fa.fa-facebook:hover{ background-color: hsl(221, 100%, 50%);}
        .fa.fa.fa-twitter:hover{ background-color: #157dcc;}
        .fa.fa-linkedin:hover{background-color:  #00aeffd3;}
        
    </style>
    <body>
        <header  style="position:sticky;top:-12px;background-color:#12c064;">
            <div id = 'header'>
                <span class = 'logo'>
                    <div id="mySidenav" class="sidenav">
                        <div>
                            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                        </div>
                        {% if request.user.is_authenticated %}
                        <a style="float:left;position: relative; left:30px" href="{% url 'Hotel:showbookings' %}">Show my bookings</a>
                        <a style="float:left;position: relative; left:30px" href="{% url 'Hotel:editprofile' %}">Edit profile</a>
                        <a style="float:left;position: relative; left:30px" href="{% url 'Hotel:password_change' %}">Change password</a>
                        <a style="float:left;position: relative; left:30px" href='{% url "Hotel:cancellation" %}'>Cancellation info</a>
                        <a style="float:left;position: relative; left:30px" href='{% url "Hotel:logout" %}'>Logout</a>
                        {% else %}
                        <a style="float:left;position: relative; left:30px" href='{% url "Hotel:register" %}'>Register</a><br>
                        <a style="float:left;position: relative; left:30px" href='{% url "Hotel:login" %}'>Login</a>
                        {% endif %}
                    </div>
                      <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
                      <script>
                        function openNav() {
                          document.getElementById("mySidenav").style.width = "250px";
                        }
                        
                        function closeNav() {
                          document.getElementById("mySidenav").style.width = "0";
                        }
                        </script>
                </span>
                {% if request.user.is_authenticated %}
                <ul class="menu">   
                    
                    <li {% if section == "dashboard" %}class="selected"{% endif %}>
                        <a href='{% url "Hotel:dashboard" %}'>Home</a>
                    </li>
                    <li {% if section == "about_us" %}class="selected"{% endif %}>
                        <a href="{% url 'Hotel:aboutus' %}">About us</a>
                    </li>
                    <li {% if section == "book_a_room" %}class="selected"{% endif %}>
                        <a href="{% url 'Hotel:room_details' %}">Rooms</a>
                    </li>
                    <li {% if section == "gallery" %}class="selected"{% endif %}>
                        <a href="{% url 'Hotel:gallery' %}">Gallery</a>
                    </li>
                    <li {% if section == "contact" %}class="selected"{% endif %}>
                        <a href="{% url 'Hotel:contact' %}">Contact us</a>
                    </li>
                </ul>
                {% endif %}
                <span class="user">
                {% if request.user.is_authenticated %}
                    Hello {{ request.user.first_name|default:request.user.username }}&nbsp
                    <!-- <div style="display: inline-block;">
                        <div>
                            <a href="{% url 'Hotel:editprofile' %}">Edit profile</a>
                            <a href="{% url 'Hotel:showbookings' %}">Show my bookings</a>
                            {% comment %} <a href="#">Print bill</a> {% endcomment %}
                            {% comment %} <a href="#">Change password</a> {% endcomment %}
                            {% comment %} <a href="#">Logout</a> {% endcomment %}
                        </div>
                    </div>
                    <a href='{% url "Hotel:logout" %}'>Logout</a>&nbsp&nbsp
                    <a href="{% url 'Hotel:password_change' %}">Change password</a>
                 -->
               
                {% else %}
                    <a href='{% url "Hotel:login" %}'>Log-in</a>
                {% endif %}
                </span>
            </div>
        </header>
        <div id = 'content'>
            {% block content %}
            {% endblock content %}
        </div>
        <footer>
            <div>
                <center><p id="foo">Get In Touch</p><br><br>
                <center>
                <div id="fodiv">
                    <a href="#" class="fa fa-facebook"></a> 
                    <a href="#" class="fa fa-twitter"></a> 
                    <a href="#" class="fa fa-linkedin"></a>
                    <a href="#" class="fa fa-instagram"></a>  
                    <a href="#" class="fa fa-youtube"></a>   
                </div>
                <br>
                <br>
                <br><br>
                </center>
                <div>
                    <div  style="text-align: justify;display: grid;grid-template-columns: 1fr 3fr;padding-left: 70px;">
                        <div>
                            <img src="/static/images/footer.png" alt=""><br>
                            <span style="color: #71302d;;">PRIDE HOTELS LIMITED</span>
                                <p>
                                    THE RUBY, 5TH FLOOR, OFFICE NO.5 SC, SOUTH WING ON LEVEL 8TH, SENAPATI BAPAT MARG,<br>
                                    MUMBAI – 400 028
                                </p>
                                    <div >
                                        <a href="#" style="background-color:  #cdebc9; color: #71302d;" class="fa fa-facebook"></a> 
                                        <a href="#" style="background-color:  #cdebc9;color: #71302d;"class="fa fa-twitter"></a> 
                                        <a href="#" style="background-color:  #cdebc9;color: #71302d;"class="fa fa-linkedin"></a>
                                        <a href="#" style="background-color:  #cdebc9;color: #71302d;"class="fa fa-instagram"></a>  
                                        <a href="#" style="background-color:  #cdebc9;color: #71302d;"class="fa fa-youtube"></a>   
                                    </div>
                        </div>
                        <div>
                            <!-- <hr width="400%" style="position: relative; left: -500px;"> -->
                            <center>
                                <div>
                                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d56073.03801839432!2d77.05296465820312!3d28.552795699999997!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390d1c69a0e02065%3A0x19b905d117e1214!2sPride%20Plaza%20Hotel%20Aerocity%2C%20New%20Delhi!5e0!3m2!1sen!2sin!4v1679994676218!5m2!1sen!2sin" width="600" height="300" style="border:0;float: right;margin-right: 70px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                                </div>
                            </center>
                        </div>
                    </div>
                    <br>
                    <hr width="60%">
                    <ul style="display: inline-flex;list-style: none;">   
                        <li>
                            <a  style="color: #71302d;" href='{% url "Hotel:dashboard" %}'>Home</a>&nbsp;&nbsp;&nbsp;
                        </li>
                        <li>
                            <a  style="color: #71302d;" href="{% url 'Hotel:aboutus' %}">About us</a>&nbsp;&nbsp;&nbsp;
                        </li>
                        <li>
                            <a  style="color: #71302d;" href="{% url 'Hotel:room_details' %}">Rooms</a>&nbsp;&nbsp;&nbsp;
                        </li>
                        <li>
                            <a  style="color: #71302d;" href="#">Gallery</a>&nbsp;&nbsp;&nbsp;
                        </li>
                        <li>
                            <a style="color: #71302d;" href="{% url 'Hotel:contact' %}">Contact us</a>&nbsp;&nbsp;&nbsp;
                        </li>
                    </ul>
                </div>
            </div>
            <center>
                <p style="font-size: 15px;margin-top: -10px;margin-bottom: 0px;">&copy;2023 The Pride Plaza Hotel,All rights reserved.</p>
            </center>
        </footer>
    </body>
</html>

HBS/Hotel/templates/booking_form.html
{% extends 'base.html' %}
{% block title %}Booking form{% endblock title %}
{% block content %}
<h1>Booking form</h1>
<p style ="font-size:20px;">Pls verify details for booking</p>
<form method = 'post' action="{% url 'Hotel:booking_form' %}">
    {% if form.errors %}
        </p>this is a error</p>
    {% endif %}
    {% csrf_token %}
    <span style ="display:flex;padding: 0px 800px 0px 0px;">
        <p>
            <label for="id_First_name">First name:</label>
            <input type="text" name="First_name" value = '{{request.user.first_name}}' required id="id_First_name">
          </p>
          <p>
            <label for="id_Last_name">Last name:</label>
            <input type="text" name="Last_name" value = '{{request.user.last_name}}' required id="id_Last_name">
          </p>
          <p>
            <label for="id_Email">Email:</label>
            <input type="email" name="Email" required value = '{{request.user.email}}' id="id_Email">
          </p>
    </span>
    <span style ="display:flex;    padding: 0px 800px 0px 0px;">
        <p>
            <label for="id_Room_no">Room no:</label>
            <input type="number" name="Room_no" required value="{{room.room_no}}" readonly id="id_Room_no">
          </p>
          <p>
            <label for="id_Room_type">Room type:</label>
            <input type="text" name="Room_type" required value="{{room.room_type}}" readonly id="id_Room_type">
          </p>
          <p>
              <label for="id_Beds">Beds:</label>
              <input type="number" name="Beds" required value="{{room.beds}}" readonly id="id_Beds">
            </p>
    </span>
    <span style ="display:flex;    padding: 0px 800px 0px 0px;">
      <p>
        <label for="id_Capasity">Capasity:</label>
        <input type="number" name="Capasity" required value="{{room.capasity}}" readonly id="id_Capasity">
      </p>
        <p>
            <label for="id_check_in">Check in:</label>
            <input type="date" name="check_in" required value="{{checkin}}" readonly id="id_check_in">
          </p>
          <p>
              <label for="id_check_out">Check out:</label>
              <input type="date" name="check_out" required value="{{checkout}}" readonly id="id_check_out">
          </p>
          
    </span>
    <span style ="display:flex;padding: 0px 1150px 0px 0px;">
        <p>
            <label for="id_total_price">Total price:</label>
            <input type="number" name="total_price" required value="{{ amount }}" readonly id="id_total_price">
        </p>
        <p>
            <label for="id_username">Username:</label>
            <input type="text" name="username"  readonly value='{{request.user.username}}'  maxlength="150" required="" id="id_username">
          </p>
    </span>
    <p><input type = 'submit'name ="booking" value='Make payment'></p>
</form>
{% endblock content %}